/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package game;

import city.cs.engine.World;

/**
 * class is a JPanel that adds the gui buttons <br>
 * pause, resume, and quit.
 * @author Trevor, Oluotch, Trevor.Oluotch@city.ac.uk <br>
 * @version 3.0<br>
 * @since version 1.0<br>
 */
public class ControlPanel extends javax.swing.JPanel {

    /** Creates new world instance */
    private World world;
    
    /**
     *Constructor with the parameter world parsed through
     * @param world
     * game world the player is in
     */
    public ControlPanel(World world) {
        this.world = world;
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Quit = new javax.swing.JButton();
        Pause = new javax.swing.JButton();
        Resume = new javax.swing.JButton();

        Quit.setText("Quit");
        Quit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuitActionPerformed(evt);
            }
        });

        Pause.setText("Pause");
        Pause.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PauseActionPerformed(evt);
            }
        });

        Resume.setText("Resume");
        Resume.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResumeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(Resume)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Pause)
                .addGap(18, 18, 18)
                .addComponent(Quit)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Pause)
                    .addComponent(Quit)
                    .addComponent(Resume))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
/**
 * method controls the action performed when quit button is pressed <br>
 * the game is exited
 * @param evt 
 * action event that is triggered when button is pressed
 */
    private void QuitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_QuitActionPerformed
/**
 * method controls the action performed when pause button is pressed <br>
 * the game is paused
 * @param evt 
 * action event that is triggered when button is pressed
 * 
 */
    private void PauseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PauseActionPerformed
        // TODO add your handling code here:
        world.stop();
    }//GEN-LAST:event_PauseActionPerformed
/**
 * method controls the action performed when resume button is pressed <br>
 * the game is resumed
 * @param evt 
 * action event that is triggered when button is pressed
 *  
 */
    private void ResumeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResumeActionPerformed
        // TODO add your handling code here:
        world.start();
    }//GEN-LAST:event_ResumeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Pause;
    private javax.swing.JButton Quit;
    private javax.swing.JButton Resume;
    // End of variables declaration//GEN-END:variables

}
