/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package game;

import city.cs.engine.SoundClip;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import static game.Game.scoreSheet;
import static game.Game.jf;
import javax.sound.sampled.LineUnavailableException;
import javax.sound.sampled.UnsupportedAudioFileException;
import javax.swing.JFrame;



/**
 *start menu when game is started that allows user to navigate to different 
 * @author  Trevor, oluotch, Trevor.Oluotch@city.ac.uk
 * @version 3.0
 * @since version 1.0
 */
public class StartMenu extends javax.swing.JPanel {

    /**
     * game music thats played at beginning of game
     */
    
     private SoundClip gameMusic;
     
    /**
     *Creates new form StartMenu
     */
    public StartMenu() {
        initComponents();
        
                         try {
            gameMusic = new SoundClip("data/power.mp3"); 
            gameMusic.loop();
        } catch (UnsupportedAudioFileException|IOException|LineUnavailableException e) {
            System.out.println(e);
        }
    }
    
     

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        playButton = new javax.swing.JButton();
        rules = new javax.swing.JButton();
        leaderBoard = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        username = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setLayout(null);

        playButton.setFont(new java.awt.Font("Berlin Sans FB", 1, 11)); // NOI18N
        playButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/play-icon.png"))); // NOI18N
        playButton.setText("Play");
        playButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playButtonActionPerformed(evt);
            }
        });
        add(playButton);
        playButton.setBounds(180, 320, 100, 30);

        rules.setFont(new java.awt.Font("Berlin Sans FB", 1, 11)); // NOI18N
        rules.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/rules-icon.png"))); // NOI18N
        rules.setText("Rules");
        rules.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rulesActionPerformed(evt);
            }
        });
        add(rules);
        rules.setBounds(20, 320, 140, 30);

        leaderBoard.setFont(new java.awt.Font("Berlin Sans FB", 1, 11)); // NOI18N
        leaderBoard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/leaderboard-icon.png"))); // NOI18N
        leaderBoard.setText("LeaderBoard");
        leaderBoard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leaderBoardActionPerformed(evt);
            }
        });
        add(leaderBoard);
        leaderBoard.setBounds(300, 320, 150, 30);

        jTextField1.setFont(new java.awt.Font("Berlin Sans FB", 1, 24)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(51, 255, 0));
        jTextField1.setText("Space Race");
        jTextField1.setBorder(null);
        jTextField1.setOpaque(false);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        add(jTextField1);
        jTextField1.setBounds(180, 0, 130, 50);

        username.setBackground(new java.awt.Color(255, 204, 0));
        username.setText("name");
        username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameActionPerformed(evt);
            }
        });
        add(username);
        username.setBounds(70, 170, 210, 20);

        jButton4.setText("Enter");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        add(jButton4);
        jButton4.setBounds(290, 170, 80, 20);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setForeground(new java.awt.Color(255, 102, 102));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/menuBackground.jpg"))); // NOI18N
        add(jLabel2);
        jLabel2.setBounds(0, 0, 500, 380);
    }// </editor-fold>//GEN-END:initComponents
                 /**
                  * creates rule page from button click
                  * @param evt 
                  * takes user to rule page where they view the rules
                  */
    private void rulesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rulesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rulesActionPerformed
                  /**
                   * displays game title
                   * @param evt
                   * no action performed
                   */
    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed
             /**
              * plays the game
              * @param evt 
              * takes player to game world level 1
              */
    private void playButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playButtonActionPerformed
        Game.jf.dispose();
        gameMusic.stop();
         try {
             Game g = new Game();
             String name = username.getText();
             MyView.name = name;
             //Game.pName = name;
             
             
         } catch (IOException ex) {
             Logger.getLogger(StartMenu.class.getName()).log(Level.SEVERE, null, ex);
         }
        
    }//GEN-LAST:event_playButtonActionPerformed
                /**
                 * go to leader board page wit scores
                 * @param evt
                 *  goes to leader board page with scores
                 */
    private void leaderBoardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leaderBoardActionPerformed
        HighScore start =  new HighScore();
        start.setVisible(true);
        
        scoreSheet.setSize(500, 500);
        scoreSheet.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        scoreSheet.setVisible(true);
        scoreSheet.add(start);
        jf.dispose();
    }//GEN-LAST:event_leaderBoardActionPerformed
                 /**
          * enter name
          * @param evt
          * enter name
          */
    private void usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameActionPerformed
          /**
           * writes name to text file
           * @param evt
           * writes name to text file
           */
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        WriteFile data = new WriteFile("sample.txt",true);
         try {
             data.writeToFile(username.getText());
             System.out.println("Name Printed");
         } catch (IOException ex) {
             Logger.getLogger(StartMenu.class.getName()).log(Level.SEVERE, null, ex);
         }
    }//GEN-LAST:event_jButton4ActionPerformed
        
      

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton leaderBoard;
    private javax.swing.JButton playButton;
    private javax.swing.JButton rules;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
